--
-- Dumping data for table `admin`
--

INSERT INTO `admin` (`id`, `username`, `password`) VALUES
(11, 'admin', '$2y$10$cR4qtd7EqCnkUrg4DVIzvePa5UqCzGNMlEAWyO/4DTCEt1T/sPhea');

--
-- Dumping data for table `posts`
--

INSERT INTO `posts` (`id`, `title`, `body`, `postedAt`, `IsHomepage`) VALUES
(8, '', '<h1>Welcome to my Blog!</h1>\r\n<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum debitis accusamus fuga reprehenderit error similique inventore quod sequi quibusdam fugit, magni deserunt iusto, nobis eum? Error odio mollitia, deserunt velit reprehenderit hic autem rem fugit numquam reiciendis eius dolores saepe delectus excepturi modi consectetur id nulla deleniti, dicta et ipsa alias aliquid vero.</p>\r\n<p>Harum officia illum quaerat, eveniet ex laudantium magnam consequuntur quasi obcaecati aliquam alias iusto fugiat dignissimos officiis, vitae eum repudiandae. Odit beatae dicta modi iste, necessitatibus ducimus ipsam? Aut magni quo deleniti minus quaerat, similique dolor laudantium cupiditate id molestias sit velit explicabo temporibus rem. Optio, aspernatur.</p>\r\n<p>&#x1f4f2; +370 123 456789</p>\r\n<p>✉ t.blog@example.com</p>', '2020-11-14 16:38:25', 1),
(9, 'about me', '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>\r\n<p>Tempora voluptatem numquam illum suscipit illo debitis eius earum fuga voluptates, veritatis iusto expedita itaque rem voluptatum tempore explicabo aut mollitia sequi blanditiis animi dolorum.</p>\r\n<p>Suscipit blanditiis dolorem officiis numquam tempore expedita quibusdam rem, labore ducimus culpa impedit! Explicabo facilis, quos odit iusto aliquid totam, itaque tenetur sint minima numquam nam dolores, ad unde nostrum! Labore, assumenda cupiditate deleniti cumque repellendus quae, eligendi ut obcaecati facilis animi debitis nostrum accusantium quibusdam, ab provident ad cum laudantium magni iste non.</p>\r\n<p>Impedit ipsum dicta veritatis eius facere! In, magni dolor deserunt nulla voluptatum libero ad perferendis delectus hic fuga, beatae ut, eligendi unde dolore iusto rerum natus provident nobis minima laudantium odit! Quasi neque voluptatem officia expedita at optio labore recusandae id odit blanditiis maiores, quidem aspernatur dignissimos! Suscipit molestiae assumenda amet, repudiandae reiciendis recusandae modi.</p>\r\n<p>Iusto repellendus veniam autem doloribus. Ut, dolores officiis!</p>', '2020-11-14 16:38:25', 0),
(10, 'storyline', '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>\r\n<p>Id numquam iste facilis expedita deleniti, exercitationem praesentium quas quia ad quibusdam asperiores provident qui quos sed laborum ullam voluptatum, veritatis, maxime molestiae obcaecati maiores modi autem voluptatibus porro.</p>\r\n<p>Laudantium impedit nam, voluptatem voluptatibus hic nostrum sint magni nemo sequi! Porro, maiores sunt beatae exercitationem eaque cupiditate fuga molestias consectetur reprehenderit assumenda sint at magni aspernatur animi repudiandae.</p>\r\n<p>Repellendus exercitationem doloribus ducimus aperiam aliquam, possimus cupiditate blanditiis autem ad consequatur, deleniti iste molestias recusandae libero nihil soluta voluptatum quae quaerat omnis, dicta eaque dolorum dolores quas! Sequi, recusandae? Sequi ducimus, maxime mollitia autem asperiores ad praesentium, facilis reprehenderit id quo aperiam neque aspernatur soluta iure, voluptates nesciunt veritatis adipisci numquam iste odit!</p>', '2020-11-14 18:12:53', 0);
